version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - BCP
  - Bollinger
  - Bradner
  - Bredon
  - CCC
  - CLA
  - CLP
  - clsa
  - CMF
  - datatypes
  - DOI
  - Douklias
  - Farrington
  - figcaption
  - gml
  - Hulme
  - IDREFS
  - IEC
  - IEP
  - Infoset
  - IPR
  - IRI
  - Jahn
  - JAXB
  - keyref
  - KGM
  - Kondannagari
  - Korver
  - Lavdjola
  - Leiba
  - Madruga
  - Mierwa
  - NDR
  - nonconformant
  - Ordinality
  - pandoc
  - PGB
  - RDFS
  - referenceable
  - Rescorla
  - RISS
  - RQ001
  - Sparrell
  - Stathakis
  - subclassing
  - subproperties
  - subproperty
  - underspecified
  - unece
  - Unisys
  - unitless
  - UTF
  - Vamsi
  - webarch
  - xsi
ignoreWords: []
import: []
